### ISSUE TITLE
clear all deprecated elements before calling it abi3

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1777]
There's been a good deal of deprecated material collecting, which we can't remove until ABI3, intended to be marked by 3.0.0.

I've been trying to move it to the bottom of `notcurses.h` and `ncdirect.h`, but we ought do a final pass.

All shipped code ought already have moved off of deprecated material, of course.

Also look for anything we can move to a `static inline` and away from a symbol. Symbols can't be promoted to static inline, or else old programs will stop linking.

a partial list, growing as things change:

* [x] remove `renderfile` from `notcurses_options` #2081
* [x] convert all `notcurses_can_*()` functions to `static inline` wrappers around `notcurses_capabilities()` #1768 
* [x] convert all non-`inline` `ncdirect_can_*()` functions to `static inline`s around `ncdirect_capabilities()` #1768
* [x] kill all functions marked as `((deprecated))`
* [x] kill old `CELL_ALPHA_*` definitions
* [x] kill old `palette256` type
* [x] `notcurses_render_to_buffer()`,  `notcurses_render_to_file()`
* [x] `notcurses_render()` becomes `static inline`
* [x] `nccell_width()` is removed
* [x] move fields around in `ncstats` to match documentation
* [x] remove the unused third parameter from `ncdirect_getc()` and `notcurses_getc()` #1967
* [x] renumber our synthesized `NCKEY` constants to match the kitty protocol (see #2131)
* [x] `ncstrwidth` becomes `static inline` (see #2153)
* [x] remove definitions of `notcurses_getc()` and `ncdirect_getc()`
* [x] stylemask functions ought return `uint16_t` (see #2200)
* [x] `ncplane_move_below()` and `ncplane_move_above()` ought be modified to accept `NULL`, with obvious implications, and `ncplane_move_top()` and `ncplane_move_bottom()` can be rewritten as `static inlines` around them, cutting two symbols
* [x] rename `ncplane_pixelgeom` to `ncplane_pixel_geom`
* [x] rename `ncplane_moverel` to `ncplane_move_rel`
* [x] change all geometry params and especially returns from `int` to `unsigned`
* [x] require `ncpile*` (from `ncplane*`) instead of `notcurses*` for `ncvisual_render()`, `NULL` for new pile (#1462)
* [x] `notcurses_get()` ought take an absolute deadline rather than a delay bound. kill off `delaybound_to_deadline()` once this is done (see #2302)
* [x] `ncdirect_rounded_box()` and `ncdirect_double_box()` ought become `static inline`
* [x] `notcurses_top()` and `notcurses_bottom()` can become static inlines around `ncpile_{top, bottom}()`
* [x] `ncmetric()` can become `static inline`

you know, maybe we don't want to nuke everything that's deprecated; where possible, we could keep them as (deprecated) `static inline`s, so a recompile still works. maybe.

rejected:

*~~`ncplane_erase()` becomes static inline around `ncplane_erase_region()`, which calls the current internal `ncplane_erase()` for that special case (it's a good optimization)~~ (dumb idea. this would just require traversing all the checks in `ncplane_erase_region()` for no good reason)
* ~~`notcurses_getvec()` can become static inline~~ the whole point of `notcurses_getvec()` is speed, and we can be faster if we embed this behind the locking

**Comment by dankamongmen** [comment]
so ought we deprecate `notcurses_render()`?

**Comment by joseluis** [comment]
adding to the list, in case the pointer types can be normalized:
- `ncplane_dim_yx`
- `ncplane_cursor_yx`

**Comment by dankamongmen** [comment]
> adding to the list, in case the pointer types can be normalized:
> 
> * `ncplane_dim_yx`
> * `ncplane_cursor_yx`

these both got done
